//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kval
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KontragentyEntities : DbContext
    {
        public KontragentyEntities()
            : base("name=KontragentyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FizicheskoyeLitsoSet> FizicheskoyeLitsoSet { get; set; }
        public virtual DbSet<MenedzherSet> MenedzherSet { get; set; }
        public virtual DbSet<YuridicheskoyeLitsoSet> YuridicheskoyeLitsoSet { get; set; }
    }
}
